version: '3.8'

services:
  trading-agents:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LLM_PROVIDER=openrouter
      - BACKEND_URL=https://openrouter.ai/api/v1
      - PORT=8080
      # Uncomment and set your API key below
      # - API_KEY=your_openrouter_api_key_here
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
    # If you want to use environment variables from a file, uncomment the line below
    # env_file:
    #   - .env